config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/about" => "homes#about" ,as: "about"
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites,only:[:create,:destroy,:index]
    resources :post_comments,only:[:create,:destroy]
  end
  resources :users,only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings" ,as: "followings"
    get "followers" => "relationships#followers" ,as: "followers"
  end
  get "/search" => "searchs#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many:favorites,dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id:user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true,length:{maximum:200}
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title LIKE ?", "%#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  # ユーザーをフォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    followings.include?(user)
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE ?","%#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end
  attachment :profile_image

  validates :name,length:{minimum: 2,maximum: 20},uniqueness:true
  validates :introduction,length:{maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    else
      @books = Book.all
      render"index"
    end
    flash[:success] = "You have created book successfully."
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @post_comment = PostComment.new
    @post_comments = PostComment.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      render"edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      @books = Book.all
      render"edit"
    end
    flash[:success] = "You have updated book successfully."
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end

    def about
    end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.book_id = @book.id
    @post_comment.user_id = current_user.id
    @post_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @post_comment = @book.post_comments.find(params[:id])
    @post_comment.destroy
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
		redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
		redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render"edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render"edit"
    end
    flash[:success] = "You have updated user successfully."
  end

  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book,local:true do |f|%>
      <div class="field">
        <label>Title</label><br>
        <%= f.text_area:title %>
      </div>
      <div class="field">
        <label>Opinion</label><br>
        <%= f.text_area:body %>
      </div>
      <div class="action">
        <%= f.submit'Update Book',class: 'btn btn-success' %>
      </div>
      <% end %>
      <%= link_to "Show",book_path(@book) %>
      |
      <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
<% end %>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <table class="table">
                 <tbody>
                    <tr>
                      <th>name</th>
                      <th>
                        <%= current_user.name %>
                      </th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th>
                         <%= current_user.introduction %>
                        </th>
                    </tr>
                    <tr>
                        <th>follows</th>
                        <th><%= link_to current_user.followings.count,user_followings_path(current_user) %></th>
                    </tr>
                    <tr>
                        <th>followers</th>
                        <th><%= link_to current_user.followers.count,user_followings_path(current_user) %></th>
                    </tr>
                 </tbody>
             </table>
             <% if current_user == current_user %>
             <% if current_user.following?(current_user) %>
                <%= link_to "フォロー外す", user_relationships_path(current_user.id),method: :delete,class: 'btn btn-info' %>
                <% else %>
                <%= link_to "フォローする", user_relationships_path(current_user.id),method: :post,class: 'btn btn-info' %>
                <% end %>
             <% end %>
             <div class="row">
                    <%= link_to edit_user_path(current_user.id),class: "btn btn-outline-secondary btn-block" do %>
                    <i class="fas fa-user-cog"></i>
                    <% end %>
             </div>
             <h2>New book</h2>
             <%= form_with model: @book,local:true do |f| %>
             <div class="field">
              <label>Title</label><br>
              <%= f.text_field:title %>
             </div>
             <div class="field">
              <label>Opinion</label><br>
               <%= f.text_area:body %>
             </div>
             <div class="action">
               <%= f.submit'Create Book',class: "action btn btn-success" %>
             </div>
             <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr id="book_<%= book.id %>">
                <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"),user_path(book.user_id) %></td>
                <td><%= link_to book.title,book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td class="favorite">
                    <%= render'favorites/favorite',book: book %>
                </td>
                <td><p>コメント数:<%= book.post_comments.count %></p></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<%= flash[:success] %>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <table class="table">
                 <tbody>
                    <tr>
                      <th>name</th>
                      <th>
                        <%= @book.user.name %>
                      </th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th>
                          <%= @book.user.introduction %>
                        </th>
                    </tr>
                    <tr>
                        <th>follows</th>
                        <th><%= link_to @book.user.followings.count,user_followings_path(@book.user) %></th>
                    </tr>
                    <tr>
                        <th>followers</th>
                        <th><%= link_to @book.user.followers.count,user_followers_path(@book.user) %></th>
                    </tr>
                 </tbody>
             </table>
             <div>
                <% unless @book.user == current_user %>
                <% if current_user.following?(@book.user) %>
                <%= link_to "フォロー外す", user_relationships_path(@book.user.id),method: :delete,class: 'btn btn-info' %>
                <% else %>
                <%= link_to "フォローする", user_relationships_path(@book.user.id),method: :post,class: 'btn btn-info' %>
                <% end %>
                <% end %>
             </div>
             <% if @book.user.id == current_user.id %>
             <div class="row">
                <%= link_to edit_user_path(@book.user.id),class: "btn btn-outline-secondary btn-block" do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
             </div>
             <% end %>
             <h2>New book</h2>
             <%= form_with model: @newbook,local:true do |f| %>
             <div class="field">
              <label>Title</label><br>
              <%= f.text_field:title %>
             </div>
             <div class="field">
              <label>Opinion</label><br>
               <%= f.text_area:body %>
             </div>
             <div class="action">
               <%= f.submit'Create Book',class: "action btn btn-success" %>
             </div>
             <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <thead>
            </thead>
            <tbody>
              <tr id="book_<%= @book.id %>">
                <td><%= link_to attachment_image_tag(@book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"),user_path(@book.user_id) %><br>
                    <%= link_to @book.user.name,user_path(@book.user) %></td>
                <td><%= link_to @book.title,books_path(@book.id) %></td>
                <td><%= @book.body %></td>
                <% if user_signed_in? && current_user.id == @book.user_id %>
                <td>
                  <%= link_to "Edit",edit_book_path(@book),class: 'btn btn-success' %>
                </td>
                <td>
                  <%= link_to "Destroy",book_path(@book),method: :delete,class: 'btn btn-danger',"data-confirm"=>"本当に消しますか？" %>
                </td>
                <% end %>
                <td class="favorite">
                    <%= render'favorites/favorite', book: @book %>
                </td>
                <td>
                  <p>コメント数:<%= @book.post_comments.count %></p>
                </td>
              </tr>
            </tbody>
          </table>
          <table class="book_<%= @book.id %>">
          <%= render'post_comments/post_comment', book: @book %>
          </table>
          <%= render'post_comments/form', book: @book, post_comment: @post_comment %>
        </div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book.favorites.count,book_favorites_path(book), method: :delete, remote: true, class: 'text-danger fas fa-heart heart_red' %>
<% else %>
    <%= link_to book.favorites.count,book_favorites_path(book), method: :post, remote: true, class: 'fas fa-heart heart_blue' %>
<% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to
              <i class="fas fa-book"></i>
              <strong>Bookers!!</strong>
            </h1>
          </div>
        </div>
</div>

app/views/homes/top.html.erb
<div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to
              <i class="fas fa-book"></i>
              <strong>Bookers!!</strong>
            </h1>
            <p>
              In
              <i class="fas fa-book"></i>
              <strong>Bookers</strong>
              ,
            </p>
            <p>you can share and exchange your opinions , inpsressions , and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 max-auto">
              <div class="row">
                <%= link_to "Log in", new_user_session_path,class: 'btn btn-info btn-block mb-3' %>
                <%= link_to "Sign Up", new_user_registration_path,class: 'btn btn-success btn-block mb-3' %>
              </div>
            </div>
          </div>
        </div>
  </div>

app/views/post_comments/_form.html.erb
<%= form_with(model:[book, post_comment]) do |f| %>
<%= f.text_area :comment, size: "90x5" %><br>
<%= f.submit "送信" %>
<% end %>

app/views/post_comments/_post_comment.html.erb
<% book.post_comments.each do |post_comment| %>
  <%= link_to attachment_image_tag(post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"),user_path(book.user_id) %>
  <%= post_comment.comment %>
  <% if post_comment.user == current_user %>
  <%= link_to "Destroy", book_post_comment_path(post_comment.book_id, post_comment.id), method: :delete, remote: true, class: 'btn btn-danger' %><br>
  <% end %>
  <%= link_to book.user.name,user_path(book.user_id) %></td>
  <% end %>

app/views/post_comments/create.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'post_comments/post_comment', book: @book) %>");
$(".post_comments").html("<%= j(render 'post_comments/form', book: @book, post_comment: @post_comment) %>");
$("textarea").val('')

app/views/post_comments/destroy.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'post_comments/post_comment', book: @book) %>");
$(".post_comments").html("<%= j(render 'post_comments/form', book: @book, post_comment: @post_comment) %>");
$("textarea").val('')

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searchs/search.html.erb
<table class='table'>
  <% if @range == "User" %>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Introduction</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <% @users.each do |user| %>
    <tbody>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
      </tr>
    </tbody>
    <% end %>
  <% else %>
    <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <% @books.each do |book| %>
    <tbody>
      <tr>
        <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"),user_path(book.user_id) %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
    </tbody>
    <% end %>
  <% end %>
</table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
<%= form_with model: @user,local:true do |f| %>
<div class="field">
 <label>Name</label><br>
<%= f.text_field:name %>
</div>
<div class="field">
  <label for="inputImage">Image</label><br>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
</div>
<div class="field">
 <label>Introduction</label><br>
 <%= f.text_area:introduction,autofocus:true %>
</div>
<div class="action">
 <%= f.submit'Update User',class: "action btn btn-secondary" %>
</div>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <table class="table">
                 <tbody>
                    <tr>
                      <th>name</th>
                      <th>
                    　　<% if user_signed_in? %>
                        <%= current_user.name %>
                        <% end %>
                      </th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th>
                            <%= current_user.introduction %>
                        </th>
                    </tr>
                 </tbody>
            </table>
             <div class="row">
                <%= link_to edit_user_path(current_user.id),class: "btn btn-outline-secondary btn-block" do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
             </div>
             <h2>New book</h2>
             <%= form_with model: @book,local:true do |f| %>
             <div class="field">
              <label>Title</label><br>
              <%= f.text_field:title %>
             </div>
             <div class="field">
              <label>Opinion</label><br>
               <%= f.text_area:body %>
             </div>
             <div class="action">
               <%= f.submit'Create Book',class: "action btn btn-success" %>
             </div>
             <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to "Show",user_path(user) %>
                </td>
                <td>
                    <% if current_user.following?(user) %>
                    <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete %>
                    <% else %>
                    <%= link_to "フォローする",user_relationships_path(user.id),method: :post %>
                    <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= flash[:success] %>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <table class="table">
                 <tbody>
                    <tr>
                      <th>name</th>
                      <th>
                    　　<%= @user.name %>
                      </th>
                    </tr>
                    <tr>
                      <th>introduction</th>
                      <th>
                        <%= @user.introduction %>
                      </th>
                    </tr>
                    <tr>
                        <th>follows</th>
                        <th><%= link_to @user.followings.count,user_followings_path(@user) %></th>
                    </tr>
                    <tr>
                        <th>followers</th>
                        <th><%= link_to @user.followers.count,user_followers_path(@user) %></th>
                    </tr>
                 </tbody>
             </table>
             <div>
                <% unless @user == current_user %>
                <% if current_user.following?(@user) %>
                <%= link_to "フォロー外す", user_relationships_path(@user.id),method: :delete,class: 'btn btn-info' %>
                <% else %>
                <%= link_to "フォローする", user_relationships_path(@user.id),method: :post,class: 'btn btn-info' %>
                <% end %>
                <% end %>
             </div>
             <% if @user.id == current_user.id %>
             <div class="row">
                 <%= link_to "",edit_user_path(@user.id),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
             </div>
             <% end %>
             <h2>New book</h2>
             <%= form_with model: @book,local:true do |f| %>
             <div class="field">
              <label>Title</label><br>
              <%= f.text_field:title %>
             </div>
             <div class="field">
              <label>Opinion</label><br>
               <%= f.text_area:body %>
             </div>
             <div class="action">
               <%= f.submit'Create Book',class: "action btn btn-success" %>
             </div>
             <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
             <% @books.each do |book| %>
              <tr>
                <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"),user_path(@user.id) %></td>
                <td><%= link_to book.title,book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
             <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>