config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/about" => "homes#about" ,as: "about"
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites,only:[:create,:destroy,:index]
    resources :post_comments,only:[:create,:destroy]
  end
  resources :users,only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings" ,as: "followings"
    get "followers" => "relationships#followers" ,as: "followers"
  end
  get "/search" => "searchs#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many:favorites,dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id:user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true,length:{maximum:200}
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title LIKE ?", "%#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  # ユーザーをフォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    followings.include?(user)
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE ?","%#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end
  attachment :profile_image

  validates :name,length:{minimum: 2,maximum: 20},uniqueness:true
  validates :introduction,length:{maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    else
      @books = Book.all
      render"index"
    end
    flash[:success] = "You have created book successfully."
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @post_comment = PostComment.new
    @post_comments = PostComment.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      render"edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      @books = Book.all
      render"edit"
    end
    flash[:success] = "You have updated book successfully."
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end

    def about
    end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render"edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render"edit"
    end
    flash[:success] = "You have updated user successfully."
  end

  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notification.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
   <%= content_tag (:div, value, class: #{key}) %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <%= link_to "Bookers",root_path, class: 'text-white mt-2 mb-3 nav-link text-light' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Home",user_path(current_user.id),class: 'nav-link text-light fas fa-home' %>
            </li>
            <li class="nav-item">
                <%= link_to "Users",users_path,class: 'nav-link text-light fas fa-users' %>
            </li>
            <li class="nav-item">
                <%= link_to "Books",books_path,class: 'nav-link text-light fas fa-book-open' %>
            </li>
            <li class="nav-item">
                <%= link_to "logout",destroy_user_session_path, method: :delete, class: 'nav-link text-light fas fa-sign-out-alt' %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Home",root_path,class: 'nav-link text-light fas fa-home' %>
            </li>
            <li class="nav-item">
                <%= link_to "About",about_path, class: 'nav-link text-light fas fa-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "sign up",new_user_registration_path,class: 'nav-link text-light fas fa-user-plus' %>
            </li>
            <li class="nav-item">
                <%= link_to "login",new_user_session_path,class: 'nav-link text-light fas fa-sign-in-alt' %>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <% if user_signed_in? %>
        <%= form_with url: search_path, method: :get, local: :true do |f| %>
        <%= f.text_field :word %>
        <%= f.select :range, options_for_select([['User'], ['Book']]) %>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"],["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
        <% end %>
      <% end %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="max-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_header1.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="text-white mt-2 mb-3">
            <%= link_to "Bookers",root_path, class: 'nav-link text-light' %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "Home",root_path,class: 'nav-link text-light fas fa-home' %>
            </li>
            <li class="nav-item">
                <%= link_to "About",about_path, class: 'nav-link text-light fas fa-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "sign up",new_user_registration_path,class: 'nav-link text-light fas fa-user-plus' %>
            </li>
            <li class="nav-item">
                <%= link_to "log in",new_user_session_path,class: 'nav-link text-light fas fa-sign-in-alt' %>
            </li>
            </ul>
          </div>
        </div>
      </nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_header2.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="text-white mt-2 mb-3">
            <%= link_to "Bookers",'/', class: 'nav-link text-light' %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to user_path(current_user.id),class: 'nav-link text-light'  do %>
                <i class=" fa fa-home"></i>
                Home
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to '/users',class: 'nav-link text-light' do %>
                <i class="fa fa-users"></i>
                Users
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to books_path,class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>
                Books
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa fa-sign-out-alt"></i>
                logout
                <% end %>
            </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>